<?xml version="1.0" encoding="utf-8"?>
<!--
# Copyright 2008, 2009 - Oktiva Comércio e Serviços de Informática Ltda.
#
# Este arquivo é parte do programa FILA - Sistema de Atendimento
#
# O FILA é um software livre; você pode redistribui-lo e/ou modifica-lo
# dentro dos termos da Licença Pública Geral GNU como publicada pela
# Fundação do Software Livre (FSF); na versão 2 da Licença.
#
# Este programa é distribuido na esperança que possa ser util, mas SEM
# NENHUMA GARANTIA; sem uma garantia implicita de ADEQUAÇÂO a qualquer
# MERCADO ou APLICAÇÃO EM PARTICULAR. Veja a Licença Pública Geral GNU
# para maiores detalhes.
#
# Você deve ter recebido uma cópia da Licença Pública Geral GNU, sob o
# título "LICENCA.txt", junto com este programa, se não, escreva para a
# Fundação do Software Livre(FSF) Inc., 51 Franklin St, Fifth Floor,
-->
<wsdl:definitions
  xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy"
  xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy"
  xmlns:http="http://schemas.xmlsoap.org/wsdl/http/"
  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
  xmlns:xsd="http://www.w3.org/2001/XMLSchema"
  xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
  xmlns:filatp="urn:oktiva:fila:web:tipos"
  xmlns:filasv="urn:oktiva:fila:web:servico"
  targetNamespace="urn:oktiva:fila:web:servico">

 <wsdl:types>
  <xsd:schema targetNamespace="urn:oktiva:fila:web:tipos"
   elementFormDefault="qualified">
   <xsd:element name="refresh_request" type="xsd:string" />
  </xsd:schema>
 </wsdl:types>

 <wsdl:message name="refresh_request">
  <wsdl:part name="refresh_request" element="filatp:refresh_request" />
 </wsdl:message>

 <wsdl:portType name="FilaOpiniometroCallback">
  <wsdl:operation name="iniciar_opiniometro">
   <wsdl:input message="filasv:refresh_request" />
  </wsdl:operation>
  <wsdl:operation name="encerrar_opiniometro">
   <wsdl:input message="filasv:refresh_request" />
  </wsdl:operation>
 </wsdl:portType>

 <wsdl:binding name="FilaOpiniometroCallbackSOAPXMPP" type="filasv:FilaOpiniometroCallback">
  <soap:binding transport="http://jabber.org/protocol/soap" style="rpc"/>
  <wsdl:operation name="iniciar_opiniometro">
   <soap:operation style="rpc" />
   <wsdl:input><soap:body namespace="urn:oktiva:fila:web:servico" use="literal"/></wsdl:input>
  </wsdl:operation>
  <wsdl:operation name="encerrar_opiniometro">
   <soap:operation style="rpc" />
   <wsdl:input><soap:body namespace="urn:oktiva:fila:web:servico" use="literal"/></wsdl:input>
  </wsdl:operation>
 </wsdl:binding>
 
 <wsdl:service name="FilaOpiniometroCallbackServico">
  <wsdl:port name="FilaOpiniometroCallback" binding="filasv:FilaOpiniometroCallbackSOAPXMPP">
   <soap:address location="xmpp://opiniometro@people.fila.vhost/callback/" />
  </wsdl:port>
 </wsdl:service>

</wsdl:definitions>
